import type { TestSeriesObject } from "./types"

/**
 * Frozen v107 fixtures. Written out in full on purpose: an example file that
 * spreads the previous version is not a snapshot, because editing v106 would
 * silently change what v107 asserts.
 *
 * Delta from v106: stored Perplexity providers move from the retired `sonar*`
 * models to Agent API models, and stored Vercel providers become
 * OpenAI-compatible custom providers. None of these series has either
 * provider, so they carry over unchanged; the conversions themselves are
 * covered by `v106-to-v107.test.ts`.
 */

export const testSeries: TestSeriesObject = {
  "complex-config-from-v020": {
    description: "Adds opacity to selection toolbar",
    config: {
      translationHub: {
        shortcut: "Alt+Shift+H",
        selectedProviderIds: null,
        sourceCode: null,
        targetCode: null,
        promptId: "123e4567-e89b-12d3-a456-426614174000",
      },
      siteRules: {
        userRules: [],
        disabledBuiltInRules: [],
      },
      language: {
        sourceCode: "spa",
        targetCode: "eng",
        level: "advanced",
      },
      providersConfig: [
        {
          id: "jalapenocloud-default",
          name: "Jalapeno Cloud",
          enabled: true,
          provider: "jalapenocloud",
          description: "Enterprise-grade AI used by top teams — now made for you!",
          baseURL: "https://api.jalapeno-cloud.ai/v1",
          model: {
            model: "DeepSeek-V4-Flash",
            isCustomModel: false,
            customModel: null,
          },
          providerOptions: {
            chat_template_kwargs: {
              thinking: false,
            },
          },
        },
        {
          id: "microsoft-translate-default",
          enabled: true,
          name: "Microsoft Translator",
          provider: "microsoft-translate",
        },
        {
          id: "google-translate-default",
          enabled: true,
          name: "Google Translate",
          provider: "google-translate",
        },
        {
          id: "openai-default",
          enabled: true,
          name: "OpenAI",
          provider: "openai",
          description: "Provides models like GPT-4o",
          reasoning: "none",
          apiKey: "sk-custom-prompt-key",
          baseURL: "https://api.openai.com/v1",
          model: {
            model: "gpt-4o-mini",
            isCustomModel: true,
            customModel: "translate-gpt-custom",
          },
        },
        {
          id: "deepseek-default",
          enabled: true,
          name: "DeepSeek",
          provider: "deepseek",
          description: "Recommend to use in China",
          reasoning: "none",
          apiKey: "ds-custom",
          baseURL: "https://api.custom.com/v1",
          model: {
            model: "deepseek-chat",
            isCustomModel: false,
            customModel: "",
          },
        },
        {
          id: "google-default",
          enabled: true,
          name: "Gemini",
          provider: "google",
          description: "Google's flagship AI models with advanced reasoning capabilities",
          reasoning: "none",
          model: {
            model: "gemini-2.5-pro",
            isCustomModel: false,
            customModel: "",
          },
        },
        {
          id: "deeplx-default",
          enabled: true,
          name: "DeepLX",
          provider: "deeplx",
          description: "Unofficial DeepL API",
          baseURL: "https://deeplx.vercel.app/translate",
        },
      ],
      pageTranslation: {
        providerId: "openai-default",
        mode: "translationOnly",
        modeShortcut: "Alt+Shift+M",
        enableAIContentAware: false,
        node: {
          enabled: true,
          hotkey: "alt",
          forceRetranslation: false,
        },
        page: {
          range: "all",
          autoTranslatePatterns: ["*.spanish-news.com", "*.elmundo.es"],
          neverAutoTranslatePatterns: [],
          autoTranslateLanguages: [],
          shortcut: "Alt+B",
          preload: {
            margin: 1000,
            threshold: 0,
          },
          minCharactersPerNode: 0,
          minWordsPerNode: 0,
          enableTargetLanguageSkip: true,
          skipLanguages: [],
        },
        customPromptsConfig: {
          promptId: "123e4567-e89b-12d3-a456-426614174000",
          patterns: [
            {
              id: "123e4567-e89b-12d3-a456-426614174000",
              name: "Technical Translation",
              systemPrompt: "",
              prompt:
                "Technical translation from Spanish to {{targetLanguage}}. Preserve technical terms and accuracy:\n{{input}}",
            },
          ],
        },
        requestQueueConfig: {
          capacity: 400,
          rate: 8,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        translationNodeStyle: {
          preset: "blur",
          isCustom: false,
          customCSS: null,
        },
      },
      tts: {
        defaultVoice: "en-US-GuyNeural",
        languageVoices: {
          eng: "en-US-GuyNeural",
          cmn: "zh-CN-YunxiNeural",
          "cmn-Hant": "zh-TW-YunJheNeural",
          yue: "zh-CN-YunxiNeural",
          spa: "es-ES-AlvaroNeural",
          rus: "ru-RU-DmitryNeural",
          arb: "ar-SA-HamedNeural",
          ben: "bn-BD-NabanitaNeural",
          hin: "hi-IN-MadhurNeural",
          por: "pt-BR-AntonioNeural",
          ind: "id-ID-ArdiNeural",
          jpn: "ja-JP-KeitaNeural",
          fra: "fr-FR-HenriNeural",
          deu: "de-DE-ConradNeural",
          jav: "jv-ID-DimasNeural",
          kor: "ko-KR-InJoonNeural",
          tel: "te-IN-MohanNeural",
          vie: "vi-VN-NamMinhNeural",
          mar: "mr-IN-ManoharNeural",
          ita: "it-IT-DiegoNeural",
          tam: "ta-IN-ValluvarNeural",
          tur: "tr-TR-AhmetNeural",
          urd: "ur-PK-AsadNeural",
          guj: "gu-IN-NiranjanNeural",
          pol: "pl-PL-MarekNeural",
          ukr: "uk-UA-OstapNeural",
          kan: "kn-IN-GaganNeural",
          mai: "en-US-GuyNeural",
          mal: "ml-IN-MidhunNeural",
          pes: "fa-IR-FaridNeural",
          mya: "my-MM-ThihaNeural",
          swh: "sw-KE-RafikiNeural",
          sun: "su-ID-JajangNeural",
          ron: "ro-RO-EmilNeural",
          pan: "pa-IN-OjasNeural",
          bho: "en-US-GuyNeural",
          amh: "am-ET-AmehaNeural",
          hau: "ha-NG-AbubakarNeural",
          fuv: "ff-Latn-SN-SambaNeural",
          bos: "bs-BA-GoranNeural",
          hrv: "hr-HR-SreckoNeural",
          nld: "nl-NL-MaartenNeural",
          srp: "sr-RS-NicholasNeural",
          tha: "th-TH-NiwatNeural",
          ckb: "en-US-GuyNeural",
          yor: "yo-NG-AbeoNeural",
          uzn: "uz-UZ-SardorNeural",
          zlm: "ms-MY-OsmanNeural",
          ibo: "ig-NG-EzinneNeural",
          npi: "ne-NP-SagarNeural",
          ceb: "en-US-GuyNeural",
          skr: "en-US-GuyNeural",
          tgl: "fil-PH-AngeloNeural",
          hun: "hu-HU-TamasNeural",
          azj: "az-AZ-BabekNeural",
          sin: "si-LK-SameeraNeural",
          koi: "en-US-GuyNeural",
          ell: "el-GR-NestorasNeural",
          ces: "cs-CZ-AntoninNeural",
          mag: "en-US-GuyNeural",
          run: "en-US-GuyNeural",
          bel: "be-BY-YauheniNeural",
          plt: "en-US-GuyNeural",
          qug: "en-US-GuyNeural",
          mad: "en-US-GuyNeural",
          nya: "en-US-GuyNeural",
          zyb: "en-US-GuyNeural",
          pbu: "en-US-GuyNeural",
          kin: "rw-RW-JeanNeural",
          zul: "zu-ZA-ThembaNeural",
          bul: "bg-BG-BorislavNeural",
          swe: "sv-SE-MattiasNeural",
          lin: "ln-CD-BaudouinNeural",
          som: "so-SO-MuuseNeural",
          hms: "en-US-GuyNeural",
          hnj: "en-US-GuyNeural",
          ilo: "en-US-GuyNeural",
          kaz: "kk-KZ-DauletNeural",
          heb: "he-IL-AvriNeural",
          nob: "nb-NO-FinnNeural",
          nno: "nn-NO-FinnNeural",
          afr: "af-ZA-AdriNeural",
          sqi: "sq-AL-IlirNeural",
          asm: "as-IN-BiswajitNeural",
          eus: "eu-ES-AnderNeural",
          bre: "fr-FR-HenriNeural",
          cat: "ca-ES-EnricNeural",
          cos: "fr-FR-HenriNeural",
          cym: "cy-GB-AledNeural",
          dan: "da-DK-JeppeNeural",
          div: "si-LK-SameeraNeural",
          epo: "en-US-GuyNeural",
          ekk: "et-EE-KertNeural",
          fao: "fo-FO-PoulNeural",
          fij: "en-US-GuyNeural",
          fin: "fi-FI-HarriNeural",
          fry: "nl-NL-MaartenNeural",
          gla: "en-GB-RyanNeural",
          gle: "ga-IE-ColmNeural",
          glg: "gl-ES-RoiNeural",
          grn: "es-ES-AlvaroNeural",
          hat: "fr-FR-HenriNeural",
          haw: "en-US-GuyNeural",
          hye: "hy-AM-HaykNeural",
          ido: "en-US-GuyNeural",
          ina: "en-US-GuyNeural",
          isl: "is-IS-GunnarNeural",
          kat: "ka-GE-GiorgiNeural",
          khm: "km-KH-PisethNeural",
          kir: "kk-KZ-DauletNeural",
          lao: "lo-LA-ChanthavongNeural",
          lat: "it-IT-DiegoNeural",
          lvs: "lv-LV-NilsNeural",
          lit: "lt-LT-LeonasNeural",
          ltz: "fr-FR-HenriNeural",
          mkd: "mk-MK-AleksandarNeural",
          mlt: "mt-MT-JosephNeural",
          mon: "mn-MN-BataaNeural",
          mri: "en-NZ-MitchellNeural",
          nso: "en-US-GuyNeural",
          oci: "fr-FR-HenriNeural",
          ori: "or-IN-DineshNeural",
          orm: "en-US-GuyNeural",
          prs: "en-US-GuyNeural",
          san: "hi-IN-MadhurNeural",
          slk: "sk-SK-LukasNeural",
          slv: "sl-SI-RokNeural",
          smo: "en-US-GuyNeural",
          sna: "en-US-GuyNeural",
          snd: "sd-PK-SalmanNeural",
          sot: "en-US-GuyNeural",
          tah: "fr-FR-HenriNeural",
          tat: "tt-RU-AidarNeural",
          tgk: "tg-TJ-SharifNeural",
          tir: "am-ET-AmehaNeural",
          ton: "en-US-GuyNeural",
          tsn: "en-US-GuyNeural",
          tuk: "tk-TM-AmanNeural",
          uig: "ug-CN-KashgarNeural",
          vol: "en-US-GuyNeural",
          wol: "en-US-GuyNeural",
          xho: "xh-ZA-ThembaNeural",
          ydd: "he-IL-AvriNeural",
          aka: "en-US-GuyNeural",
          bam: "fr-FR-HenriNeural",
          bis: "en-US-GuyNeural",
          bod: "zh-CN-YunxiNeural",
          che: "ru-RU-DmitryNeural",
          chv: "ru-RU-DmitryNeural",
          dzo: "zh-CN-YunxiNeural",
          ewe: "en-US-GuyNeural",
          kab: "en-US-GuyNeural",
          lug: "en-US-GuyNeural",
          oss: "ru-RU-DmitryNeural",
          ssw: "en-US-GuyNeural",
          ven: "en-US-GuyNeural",
          war: "en-US-GuyNeural",
          nde: "en-US-GuyNeural",
          nbl: "en-US-GuyNeural",
          pam: "en-US-GuyNeural",
          hil: "en-US-GuyNeural",
          bcl: "en-US-GuyNeural",
          min: "en-US-GuyNeural",
          ace: "en-US-GuyNeural",
          bug: "en-US-GuyNeural",
          ban: "en-US-GuyNeural",
          bjn: "en-US-GuyNeural",
          mak: "en-US-GuyNeural",
          sas: "en-US-GuyNeural",
          tet: "en-US-GuyNeural",
          cha: "en-US-GuyNeural",
          niu: "en-US-GuyNeural",
          tvl: "en-US-GuyNeural",
          gil: "en-US-GuyNeural",
          mah: "en-US-GuyNeural",
          pau: "en-US-GuyNeural",
          wls: "en-US-GuyNeural",
          rar: "en-US-GuyNeural",
          hif: "en-US-GuyNeural",
        },
        rate: 0,
        pitch: 0,
        volume: 0,
      },
      floatingButton: {
        enabled: true,
        position: 0.75,
        disabledFloatingButtonPatterns: ["*.github.com"],
        clickAction: "panel",
        locked: false,
        side: "right",
      },
      sideContent: {
        width: 700,
      },
      selectionToolbar: {
        order: [
          "translate",
          "speak",
          "default-dictionary",
          "default-sentence-analysis",
          "default-improve-writing",
        ],
        unpinned: ["default-improve-writing"],
        noteSuggestion: {
          enabled: true,
          actionId: "default-dictionary",
          providerId: "openai-default",
        },
        enabled: false,
        disabledSelectionToolbarPatterns: [],
        opacity: 100,
        customActions: [],
        features: {
          translate: {
            enabled: true,
            providerId: "openai-default",
            shortcut: "Alt+T",
          },
          speak: {
            enabled: true,
          },
        },
        builtInActions: {
          dictionary: {
            enabled: true,
            providerId: "deepseek-default",
          },
          sentenceAnalysis: {
            enabled: true,
            providerId: "deepseek-default",
          },
          improveWriting: {
            enabled: true,
            providerId: "deepseek-default",
          },
        },
      },
      betaExperience: {
        enabled: false,
      },
      contextMenu: {
        enabled: true,
      },
      videoSubtitles: {
        enabled: false,
        autoStart: false,
        providerId: "openai-default",
        style: {
          displayMode: "bilingual",
          translationPosition: "above",
          main: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          translation: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          container: {
            backgroundOpacity: 75,
          },
          customCSS: null,
        },
        aiSegmentation: false,
        requestQueueConfig: {
          capacity: 400,
          rate: 8,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        position: {
          percent: 10,
          anchor: "bottom",
        },
        toggleShortcut: "Alt+C",
      },
      inputTranslation: {
        enabled: true,
        providerId: "openai-default",
        fromLang: "targetCode",
        toLang: "sourceCode",
        enableCycle: false,
        timeThreshold: 300,
      },
      siteControl: {
        mode: "blacklist",
        blacklistPatterns: [],
        whitelistPatterns: [],
      },
      languageDetection: {
        mode: "basic",
        providerId: "openai-default",
      },
      uiLanguage: "auto",
      glossary: {
        enabled: true,
      },
    },
  },
  "config-with-llm-detection-enabled": {
    description:
      "Single provider, LLM detection mode; features get enabled toggles and speak added",
    config: {
      translationHub: {
        shortcut: "Alt+Shift+H",
        selectedProviderIds: null,
        sourceCode: null,
        targetCode: null,
        promptId: "default",
      },
      siteRules: {
        userRules: [],
        disabledBuiltInRules: [],
      },
      language: {
        sourceCode: "jpn",
        targetCode: "eng",
        level: "beginner",
      },
      providersConfig: [
        {
          id: "jalapenocloud-default",
          name: "Jalapeno Cloud",
          enabled: true,
          provider: "jalapenocloud",
          description: "Enterprise-grade AI used by top teams — now made for you!",
          baseURL: "https://api.jalapeno-cloud.ai/v1",
          model: {
            model: "DeepSeek-V4-Flash",
            isCustomModel: false,
            customModel: null,
          },
          providerOptions: {
            chat_template_kwargs: {
              thinking: false,
            },
          },
        },
        {
          id: "google-default",
          enabled: true,
          name: "Gemini",
          provider: "google",
          description: "Google's flagship AI models with advanced reasoning capabilities",
          reasoning: "none",
          apiKey: "goog-key",
          model: {
            model: "gemini-2.5-pro",
            isCustomModel: false,
            customModel: "",
          },
        },
      ],
      pageTranslation: {
        providerId: "google-default",
        mode: "translationOnly",
        modeShortcut: "Alt+Shift+M",
        enableAIContentAware: false,
        node: {
          enabled: true,
          hotkey: "alt",
          forceRetranslation: false,
        },
        page: {
          range: "all",
          autoTranslatePatterns: [],
          neverAutoTranslatePatterns: [],
          autoTranslateLanguages: [],
          shortcut: "Alt+B",
          preload: {
            margin: 1000,
            threshold: 0,
          },
          minCharactersPerNode: 0,
          minWordsPerNode: 0,
          enableTargetLanguageSkip: true,
          skipLanguages: [],
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        translationNodeStyle: {
          preset: "default",
          isCustom: false,
          customCSS: null,
        },
      },
      tts: {
        defaultVoice: "en-US-GuyNeural",
        languageVoices: {
          eng: "en-US-GuyNeural",
          cmn: "zh-CN-YunxiNeural",
          "cmn-Hant": "zh-TW-YunJheNeural",
          yue: "zh-CN-YunxiNeural",
          spa: "es-ES-AlvaroNeural",
          rus: "ru-RU-DmitryNeural",
          arb: "ar-SA-HamedNeural",
          ben: "bn-BD-NabanitaNeural",
          hin: "hi-IN-MadhurNeural",
          por: "pt-BR-AntonioNeural",
          ind: "id-ID-ArdiNeural",
          jpn: "ja-JP-KeitaNeural",
          fra: "fr-FR-HenriNeural",
          deu: "de-DE-ConradNeural",
          jav: "jv-ID-DimasNeural",
          kor: "ko-KR-InJoonNeural",
          tel: "te-IN-MohanNeural",
          vie: "vi-VN-NamMinhNeural",
          mar: "mr-IN-ManoharNeural",
          ita: "it-IT-DiegoNeural",
          tam: "ta-IN-ValluvarNeural",
          tur: "tr-TR-AhmetNeural",
          urd: "ur-PK-AsadNeural",
          guj: "gu-IN-NiranjanNeural",
          pol: "pl-PL-MarekNeural",
          ukr: "uk-UA-OstapNeural",
          kan: "kn-IN-GaganNeural",
          mai: "en-US-GuyNeural",
          mal: "ml-IN-MidhunNeural",
          pes: "fa-IR-FaridNeural",
          mya: "my-MM-ThihaNeural",
          swh: "sw-KE-RafikiNeural",
          sun: "su-ID-JajangNeural",
          ron: "ro-RO-EmilNeural",
          pan: "pa-IN-OjasNeural",
          bho: "en-US-GuyNeural",
          amh: "am-ET-AmehaNeural",
          hau: "ha-NG-AbubakarNeural",
          fuv: "ff-Latn-SN-SambaNeural",
          bos: "bs-BA-GoranNeural",
          hrv: "hr-HR-SreckoNeural",
          nld: "nl-NL-MaartenNeural",
          srp: "sr-RS-NicholasNeural",
          tha: "th-TH-NiwatNeural",
          ckb: "en-US-GuyNeural",
          yor: "yo-NG-AbeoNeural",
          uzn: "uz-UZ-SardorNeural",
          zlm: "ms-MY-OsmanNeural",
          ibo: "ig-NG-EzinneNeural",
          npi: "ne-NP-SagarNeural",
          ceb: "en-US-GuyNeural",
          skr: "en-US-GuyNeural",
          tgl: "fil-PH-AngeloNeural",
          hun: "hu-HU-TamasNeural",
          azj: "az-AZ-BabekNeural",
          sin: "si-LK-SameeraNeural",
          koi: "en-US-GuyNeural",
          ell: "el-GR-NestorasNeural",
          ces: "cs-CZ-AntoninNeural",
          mag: "en-US-GuyNeural",
          run: "en-US-GuyNeural",
          bel: "be-BY-YauheniNeural",
          plt: "en-US-GuyNeural",
          qug: "en-US-GuyNeural",
          mad: "en-US-GuyNeural",
          nya: "en-US-GuyNeural",
          zyb: "en-US-GuyNeural",
          pbu: "en-US-GuyNeural",
          kin: "rw-RW-JeanNeural",
          zul: "zu-ZA-ThembaNeural",
          bul: "bg-BG-BorislavNeural",
          swe: "sv-SE-MattiasNeural",
          lin: "ln-CD-BaudouinNeural",
          som: "so-SO-MuuseNeural",
          hms: "en-US-GuyNeural",
          hnj: "en-US-GuyNeural",
          ilo: "en-US-GuyNeural",
          kaz: "kk-KZ-DauletNeural",
          heb: "he-IL-AvriNeural",
          nob: "nb-NO-FinnNeural",
          nno: "nn-NO-FinnNeural",
          afr: "af-ZA-AdriNeural",
          sqi: "sq-AL-IlirNeural",
          asm: "as-IN-BiswajitNeural",
          eus: "eu-ES-AnderNeural",
          bre: "fr-FR-HenriNeural",
          cat: "ca-ES-EnricNeural",
          cos: "fr-FR-HenriNeural",
          cym: "cy-GB-AledNeural",
          dan: "da-DK-JeppeNeural",
          div: "si-LK-SameeraNeural",
          epo: "en-US-GuyNeural",
          ekk: "et-EE-KertNeural",
          fao: "fo-FO-PoulNeural",
          fij: "en-US-GuyNeural",
          fin: "fi-FI-HarriNeural",
          fry: "nl-NL-MaartenNeural",
          gla: "en-GB-RyanNeural",
          gle: "ga-IE-ColmNeural",
          glg: "gl-ES-RoiNeural",
          grn: "es-ES-AlvaroNeural",
          hat: "fr-FR-HenriNeural",
          haw: "en-US-GuyNeural",
          hye: "hy-AM-HaykNeural",
          ido: "en-US-GuyNeural",
          ina: "en-US-GuyNeural",
          isl: "is-IS-GunnarNeural",
          kat: "ka-GE-GiorgiNeural",
          khm: "km-KH-PisethNeural",
          kir: "kk-KZ-DauletNeural",
          lao: "lo-LA-ChanthavongNeural",
          lat: "it-IT-DiegoNeural",
          lvs: "lv-LV-NilsNeural",
          lit: "lt-LT-LeonasNeural",
          ltz: "fr-FR-HenriNeural",
          mkd: "mk-MK-AleksandarNeural",
          mlt: "mt-MT-JosephNeural",
          mon: "mn-MN-BataaNeural",
          mri: "en-NZ-MitchellNeural",
          nso: "en-US-GuyNeural",
          oci: "fr-FR-HenriNeural",
          ori: "or-IN-DineshNeural",
          orm: "en-US-GuyNeural",
          prs: "en-US-GuyNeural",
          san: "hi-IN-MadhurNeural",
          slk: "sk-SK-LukasNeural",
          slv: "sl-SI-RokNeural",
          smo: "en-US-GuyNeural",
          sna: "en-US-GuyNeural",
          snd: "sd-PK-SalmanNeural",
          sot: "en-US-GuyNeural",
          tah: "fr-FR-HenriNeural",
          tat: "tt-RU-AidarNeural",
          tgk: "tg-TJ-SharifNeural",
          tir: "am-ET-AmehaNeural",
          ton: "en-US-GuyNeural",
          tsn: "en-US-GuyNeural",
          tuk: "tk-TM-AmanNeural",
          uig: "ug-CN-KashgarNeural",
          vol: "en-US-GuyNeural",
          wol: "en-US-GuyNeural",
          xho: "xh-ZA-ThembaNeural",
          ydd: "he-IL-AvriNeural",
          aka: "en-US-GuyNeural",
          bam: "fr-FR-HenriNeural",
          bis: "en-US-GuyNeural",
          bod: "zh-CN-YunxiNeural",
          che: "ru-RU-DmitryNeural",
          chv: "ru-RU-DmitryNeural",
          dzo: "zh-CN-YunxiNeural",
          ewe: "en-US-GuyNeural",
          kab: "en-US-GuyNeural",
          lug: "en-US-GuyNeural",
          oss: "ru-RU-DmitryNeural",
          ssw: "en-US-GuyNeural",
          ven: "en-US-GuyNeural",
          war: "en-US-GuyNeural",
          nde: "en-US-GuyNeural",
          nbl: "en-US-GuyNeural",
          pam: "en-US-GuyNeural",
          hil: "en-US-GuyNeural",
          bcl: "en-US-GuyNeural",
          min: "en-US-GuyNeural",
          ace: "en-US-GuyNeural",
          bug: "en-US-GuyNeural",
          ban: "en-US-GuyNeural",
          bjn: "en-US-GuyNeural",
          mak: "en-US-GuyNeural",
          sas: "en-US-GuyNeural",
          tet: "en-US-GuyNeural",
          cha: "en-US-GuyNeural",
          niu: "en-US-GuyNeural",
          tvl: "en-US-GuyNeural",
          gil: "en-US-GuyNeural",
          mah: "en-US-GuyNeural",
          pau: "en-US-GuyNeural",
          wls: "en-US-GuyNeural",
          rar: "en-US-GuyNeural",
          hif: "en-US-GuyNeural",
        },
        rate: 0,
        pitch: 0,
        volume: 0,
      },
      floatingButton: {
        enabled: true,
        position: 0.5,
        disabledFloatingButtonPatterns: [],
        clickAction: "panel",
        locked: false,
        side: "right",
      },
      sideContent: {
        width: 420,
      },
      selectionToolbar: {
        order: [
          "translate",
          "speak",
          "default-dictionary",
          "default-sentence-analysis",
          "default-improve-writing",
        ],
        unpinned: ["default-improve-writing"],
        noteSuggestion: {
          enabled: true,
          actionId: "default-dictionary",
          providerId: "google-default",
        },
        enabled: true,
        disabledSelectionToolbarPatterns: [],
        opacity: 100,
        customActions: [],
        features: {
          translate: {
            enabled: true,
            providerId: "google-default",
            shortcut: "Alt+T",
          },
          speak: {
            enabled: true,
          },
        },
        builtInActions: {
          dictionary: {
            enabled: true,
            providerId: "google-default",
          },
          sentenceAnalysis: {
            enabled: true,
            providerId: "google-default",
          },
          improveWriting: {
            enabled: true,
            providerId: "google-default",
          },
        },
      },
      betaExperience: {
        enabled: false,
      },
      contextMenu: {
        enabled: true,
      },
      videoSubtitles: {
        enabled: false,
        autoStart: false,
        providerId: "google-default",
        style: {
          displayMode: "bilingual",
          translationPosition: "above",
          main: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          translation: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          container: {
            backgroundOpacity: 75,
          },
          customCSS: null,
        },
        aiSegmentation: false,
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        position: {
          percent: 10,
          anchor: "bottom",
        },
        toggleShortcut: "Alt+C",
      },
      inputTranslation: {
        enabled: true,
        providerId: "google-default",
        fromLang: "targetCode",
        toLang: "sourceCode",
        enableCycle: false,
        timeThreshold: 300,
      },
      siteControl: {
        mode: "blacklist",
        blacklistPatterns: [],
        whitelistPatterns: [],
      },
      languageDetection: {
        mode: "llm",
        providerId: "google-default",
      },
      uiLanguage: "auto",
      glossary: {
        enabled: true,
      },
    },
  },
  "prompt-token-migration-coverage": {
    description:
      "Covers legacy prompt token migration for translate, custom actions, and video subtitles",
    config: {
      translationHub: {
        shortcut: "Alt+Shift+H",
        selectedProviderIds: null,
        sourceCode: null,
        targetCode: null,
        promptId: "legacy-translate-prompt",
      },
      siteRules: {
        userRules: [],
        disabledBuiltInRules: [],
      },
      language: {
        sourceCode: "eng",
        targetCode: "cmn",
        level: "intermediate",
      },
      providersConfig: [
        {
          id: "jalapenocloud-default",
          name: "Jalapeno Cloud",
          enabled: true,
          provider: "jalapenocloud",
          description: "Enterprise-grade AI used by top teams — now made for you!",
          baseURL: "https://api.jalapeno-cloud.ai/v1",
          model: {
            model: "DeepSeek-V4-Flash",
            isCustomModel: false,
            customModel: null,
          },
          providerOptions: {
            chat_template_kwargs: {
              thinking: false,
            },
          },
        },
        {
          id: "google-default",
          enabled: true,
          name: "Gemini",
          provider: "google",
          description: "Google's flagship AI models with advanced reasoning capabilities",
          reasoning: "none",
          apiKey: "goog-key",
          model: {
            model: "gemini-2.5-pro",
            isCustomModel: false,
            customModel: "",
          },
        },
      ],
      pageTranslation: {
        providerId: "google-default",
        mode: "translationOnly",
        modeShortcut: "Alt+Shift+M",
        enableAIContentAware: false,
        node: {
          enabled: true,
          hotkey: "alt",
          forceRetranslation: false,
        },
        page: {
          range: "all",
          autoTranslatePatterns: [],
          neverAutoTranslatePatterns: [],
          autoTranslateLanguages: [],
          shortcut: "Alt+B",
          preload: {
            margin: 1000,
            threshold: 0,
          },
          minCharactersPerNode: 0,
          minWordsPerNode: 0,
          enableTargetLanguageSkip: true,
          skipLanguages: [],
        },
        customPromptsConfig: {
          promptId: "legacy-translate-prompt",
          patterns: [
            {
              id: "legacy-translate-prompt",
              name: "Legacy Translate Prompt",
              systemPrompt:
                "Translate into {{targetLanguage}} with title {{webTitle}} and summary {{webSummary}}.",
              prompt:
                "Title: {{webTitle}}\nSummary: {{webSummary}}\nTranslate to {{targetLanguage}}:\n{{input}}",
            },
          ],
        },
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        translationNodeStyle: {
          preset: "default",
          isCustom: false,
          customCSS: null,
        },
      },
      tts: {
        defaultVoice: "en-US-GuyNeural",
        languageVoices: {
          eng: "en-US-GuyNeural",
          cmn: "zh-CN-YunxiNeural",
          "cmn-Hant": "zh-TW-YunJheNeural",
          yue: "zh-CN-YunxiNeural",
          spa: "es-ES-AlvaroNeural",
          rus: "ru-RU-DmitryNeural",
          arb: "ar-SA-HamedNeural",
          ben: "bn-BD-NabanitaNeural",
          hin: "hi-IN-MadhurNeural",
          por: "pt-BR-AntonioNeural",
          ind: "id-ID-ArdiNeural",
          jpn: "ja-JP-KeitaNeural",
          fra: "fr-FR-HenriNeural",
          deu: "de-DE-ConradNeural",
          jav: "jv-ID-DimasNeural",
          kor: "ko-KR-InJoonNeural",
          tel: "te-IN-MohanNeural",
          vie: "vi-VN-NamMinhNeural",
          mar: "mr-IN-ManoharNeural",
          ita: "it-IT-DiegoNeural",
          tam: "ta-IN-ValluvarNeural",
          tur: "tr-TR-AhmetNeural",
          urd: "ur-PK-AsadNeural",
          guj: "gu-IN-NiranjanNeural",
          pol: "pl-PL-MarekNeural",
          ukr: "uk-UA-OstapNeural",
          kan: "kn-IN-GaganNeural",
          mai: "en-US-GuyNeural",
          mal: "ml-IN-MidhunNeural",
          pes: "fa-IR-FaridNeural",
          mya: "my-MM-ThihaNeural",
          swh: "sw-KE-RafikiNeural",
          sun: "su-ID-JajangNeural",
          ron: "ro-RO-EmilNeural",
          pan: "pa-IN-OjasNeural",
          bho: "en-US-GuyNeural",
          amh: "am-ET-AmehaNeural",
          hau: "ha-NG-AbubakarNeural",
          fuv: "ff-Latn-SN-SambaNeural",
          bos: "bs-BA-GoranNeural",
          hrv: "hr-HR-SreckoNeural",
          nld: "nl-NL-MaartenNeural",
          srp: "sr-RS-NicholasNeural",
          tha: "th-TH-NiwatNeural",
          ckb: "en-US-GuyNeural",
          yor: "yo-NG-AbeoNeural",
          uzn: "uz-UZ-SardorNeural",
          zlm: "ms-MY-OsmanNeural",
          ibo: "ig-NG-EzinneNeural",
          npi: "ne-NP-SagarNeural",
          ceb: "en-US-GuyNeural",
          skr: "en-US-GuyNeural",
          tgl: "fil-PH-AngeloNeural",
          hun: "hu-HU-TamasNeural",
          azj: "az-AZ-BabekNeural",
          sin: "si-LK-SameeraNeural",
          koi: "en-US-GuyNeural",
          ell: "el-GR-NestorasNeural",
          ces: "cs-CZ-AntoninNeural",
          mag: "en-US-GuyNeural",
          run: "en-US-GuyNeural",
          bel: "be-BY-YauheniNeural",
          plt: "en-US-GuyNeural",
          qug: "en-US-GuyNeural",
          mad: "en-US-GuyNeural",
          nya: "en-US-GuyNeural",
          zyb: "en-US-GuyNeural",
          pbu: "en-US-GuyNeural",
          kin: "rw-RW-JeanNeural",
          zul: "zu-ZA-ThembaNeural",
          bul: "bg-BG-BorislavNeural",
          swe: "sv-SE-MattiasNeural",
          lin: "ln-CD-BaudouinNeural",
          som: "so-SO-MuuseNeural",
          hms: "en-US-GuyNeural",
          hnj: "en-US-GuyNeural",
          ilo: "en-US-GuyNeural",
          kaz: "kk-KZ-DauletNeural",
          heb: "he-IL-AvriNeural",
          nob: "nb-NO-FinnNeural",
          nno: "nn-NO-FinnNeural",
          afr: "af-ZA-AdriNeural",
          sqi: "sq-AL-IlirNeural",
          asm: "as-IN-BiswajitNeural",
          eus: "eu-ES-AnderNeural",
          bre: "fr-FR-HenriNeural",
          cat: "ca-ES-EnricNeural",
          cos: "fr-FR-HenriNeural",
          cym: "cy-GB-AledNeural",
          dan: "da-DK-JeppeNeural",
          div: "si-LK-SameeraNeural",
          epo: "en-US-GuyNeural",
          ekk: "et-EE-KertNeural",
          fao: "fo-FO-PoulNeural",
          fij: "en-US-GuyNeural",
          fin: "fi-FI-HarriNeural",
          fry: "nl-NL-MaartenNeural",
          gla: "en-GB-RyanNeural",
          gle: "ga-IE-ColmNeural",
          glg: "gl-ES-RoiNeural",
          grn: "es-ES-AlvaroNeural",
          hat: "fr-FR-HenriNeural",
          haw: "en-US-GuyNeural",
          hye: "hy-AM-HaykNeural",
          ido: "en-US-GuyNeural",
          ina: "en-US-GuyNeural",
          isl: "is-IS-GunnarNeural",
          kat: "ka-GE-GiorgiNeural",
          khm: "km-KH-PisethNeural",
          kir: "kk-KZ-DauletNeural",
          lao: "lo-LA-ChanthavongNeural",
          lat: "it-IT-DiegoNeural",
          lvs: "lv-LV-NilsNeural",
          lit: "lt-LT-LeonasNeural",
          ltz: "fr-FR-HenriNeural",
          mkd: "mk-MK-AleksandarNeural",
          mlt: "mt-MT-JosephNeural",
          mon: "mn-MN-BataaNeural",
          mri: "en-NZ-MitchellNeural",
          nso: "en-US-GuyNeural",
          oci: "fr-FR-HenriNeural",
          ori: "or-IN-DineshNeural",
          orm: "en-US-GuyNeural",
          prs: "en-US-GuyNeural",
          san: "hi-IN-MadhurNeural",
          slk: "sk-SK-LukasNeural",
          slv: "sl-SI-RokNeural",
          smo: "en-US-GuyNeural",
          sna: "en-US-GuyNeural",
          snd: "sd-PK-SalmanNeural",
          sot: "en-US-GuyNeural",
          tah: "fr-FR-HenriNeural",
          tat: "tt-RU-AidarNeural",
          tgk: "tg-TJ-SharifNeural",
          tir: "am-ET-AmehaNeural",
          ton: "en-US-GuyNeural",
          tsn: "en-US-GuyNeural",
          tuk: "tk-TM-AmanNeural",
          uig: "ug-CN-KashgarNeural",
          vol: "en-US-GuyNeural",
          wol: "en-US-GuyNeural",
          xho: "xh-ZA-ThembaNeural",
          ydd: "he-IL-AvriNeural",
          aka: "en-US-GuyNeural",
          bam: "fr-FR-HenriNeural",
          bis: "en-US-GuyNeural",
          bod: "zh-CN-YunxiNeural",
          che: "ru-RU-DmitryNeural",
          chv: "ru-RU-DmitryNeural",
          dzo: "zh-CN-YunxiNeural",
          ewe: "en-US-GuyNeural",
          kab: "en-US-GuyNeural",
          lug: "en-US-GuyNeural",
          oss: "ru-RU-DmitryNeural",
          ssw: "en-US-GuyNeural",
          ven: "en-US-GuyNeural",
          war: "en-US-GuyNeural",
          nde: "en-US-GuyNeural",
          nbl: "en-US-GuyNeural",
          pam: "en-US-GuyNeural",
          hil: "en-US-GuyNeural",
          bcl: "en-US-GuyNeural",
          min: "en-US-GuyNeural",
          ace: "en-US-GuyNeural",
          bug: "en-US-GuyNeural",
          ban: "en-US-GuyNeural",
          bjn: "en-US-GuyNeural",
          mak: "en-US-GuyNeural",
          sas: "en-US-GuyNeural",
          tet: "en-US-GuyNeural",
          cha: "en-US-GuyNeural",
          niu: "en-US-GuyNeural",
          tvl: "en-US-GuyNeural",
          gil: "en-US-GuyNeural",
          mah: "en-US-GuyNeural",
          pau: "en-US-GuyNeural",
          wls: "en-US-GuyNeural",
          rar: "en-US-GuyNeural",
          hif: "en-US-GuyNeural",
        },
        rate: 0,
        pitch: 0,
        volume: 0,
      },
      floatingButton: {
        enabled: true,
        position: 0.5,
        disabledFloatingButtonPatterns: [],
        clickAction: "panel",
        locked: false,
        side: "right",
      },
      sideContent: {
        width: 420,
      },
      selectionToolbar: {
        order: [
          "translate",
          "speak",
          "default-dictionary",
          "default-sentence-analysis",
          "default-improve-writing",
          "coverage-action",
        ],
        unpinned: ["default-improve-writing"],
        noteSuggestion: {
          enabled: true,
          actionId: "default-dictionary",
          providerId: "google-default",
        },
        enabled: true,
        disabledSelectionToolbarPatterns: [],
        opacity: 100,
        customActions: [
          {
            id: "coverage-action",
            name: "Coverage Action",
            enabled: true,
            icon: "tabler:book-2",
            providerId: "google-default",
            systemPrompt: "Answer in {{targetLanguage}} and use {{webTitle}} as metadata.",
            prompt:
              "Selection: {{selection}}\nContext: {{paragraphs}}\nTitle: {{webTitle}}\nTarget language: {{targetLanguage}}",
            outputSchema: [
              {
                id: "coverage-term",
                name: "Term",
                type: "string",
                description: "Focus on {{selection}}.",
              },
              {
                id: "coverage-definition",
                name: "Definition",
                type: "string",
                description: "Explain it in {{targetLanguage}}.",
              },
              {
                id: "coverage-context",
                name: "Context",
                type: "string",
                description: "Reuse {{paragraphs}} exactly.",
              },
              {
                id: "coverage-notes",
                name: "Notes",
                type: "string",
                description: "Mention {{webTitle}} when relevant.",
              },
            ],
            layout: `<style>
@keyframes rf-spin{to{transform:rotate(360deg)}}
.rf-speak{box-sizing:border-box;display:inline-flex;flex:none;align-items:center;justify-content:center;width:24px;height:24px;margin:0;padding:0;border:1px solid transparent;border-radius:min(calc(var(--rf-radius, 10px) - 2px), 10px);background:transparent;background-clip:padding-box;color:var(--rf-muted-foreground);font:inherit;outline:none;user-select:none;transition:all 150ms cubic-bezier(0.4, 0, 0.2, 1)}
.rf-speak:hover{background-color:var(--rf-secondary)}
:host([data-theme=dark]) .rf-speak:hover{background-color:color-mix(in oklab, var(--rf-secondary) 50%, transparent)}
.rf-speak:focus-visible{border-color:var(--rf-ring);box-shadow:0 0 0 3px color-mix(in oklab, var(--rf-ring) 50%, transparent)}
.rf-speak:active{transform:translateY(1px)}
.rf-speak[aria-disabled=true]{opacity:0.5;pointer-events:none}
.rf-speak svg{flex:none;width:12px;height:12px;pointer-events:none}
.rf-speak .rf-i-load,.rf-speak .rf-i-stop,.rf-speak[data-speak-state=loading] .rf-i-vol,.rf-speak[data-speak-state=playing] .rf-i-vol{display:none}
.rf-speak[data-speak-state=loading] .rf-i-load{display:block;animation:rf-spin 1s linear infinite}
.rf-speak[data-speak-state=playing] .rf-i-stop{display:block}
.rf-head{display:flex;align-items:center;gap:2px;height:24px}
.rf-label{display:inline-flex;align-items:center;gap:2px;min-width:0;font-size:12px;line-height:16px;font-weight:500;color:var(--rf-muted-foreground)}
.rf-label svg{flex:none;width:12px;height:12px}
.rf-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.rf-value{font-size:14px;line-height:20px;white-space:pre-wrap;overflow-wrap:anywhere}
.rf-fields{display:flex;flex-direction:column;gap:12px}
</style>
{%- assign rf_speak = "coverage-term|coverage-context" | split: "|" -%}
<div class="rf-fields">
  {%- for f in ctx.fields %}
  <section class="rf-field" data-rf-key="{{ f.id }}">
    <div class="rf-head">
      <span class="rf-label">
        {%- if f.type == "number" -%}<svg class="rf-i-hash" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 9l14 0"/><path d="M5 15l14 0"/><path d="M11 4l-4 16"/><path d="M17 4l-4 16"/></svg>{%- else -%}<svg class="rf-i-type" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 20l3 0"/><path d="M14 20l7 0"/><path d="M6.9 15l6.9 0"/><path d="M10.2 6.3l5.8 13.7"/><path d="M5 20l6 -16l2 0l7 16"/></svg>{%- endif -%}
        <span class="rf-name">{{ f.name }}</span>
      </span>
      {%- if rf_speak contains f.id %}
      <button type="button" class="rf-speak" data-speak="{{ f.value }}"{% if f.value == blank %} aria-disabled="true"{% endif %}><svg class="rf-i-vol" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 8a5 5 0 0 1 0 8"/><path d="M17.7 5a9 9 0 0 1 0 14"/><path d="M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5"/></svg><svg class="rf-i-load" viewBox="0 0 24 24" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3a9 9 0 1 0 9 9"/></svg><svg class="rf-i-stop" viewBox="0 0 24 24" width="12" height="12" fill="currentColor" stroke="none" aria-hidden="true"><path d="M17 4h-10a3 3 0 0 0 -3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3 -3v-10a3 3 0 0 0 -3 -3z"/></svg></button>
      {%- endif %}
    </div>
    <div class="rf-value">{% if f.pending %}…{% elsif f.value == blank %}—{% else %}{{ f.value }}{% endif %}</div>
  </section>
  {%- endfor %}
</div>
`,
          },
        ],
        features: {
          translate: {
            enabled: true,
            providerId: "google-default",
            shortcut: "Alt+T",
          },
          speak: {
            enabled: true,
          },
        },
        builtInActions: {
          dictionary: {
            enabled: false,
            providerId: "read-frog-free-ai",
          },
          sentenceAnalysis: {
            enabled: true,
            providerId: "read-frog-free-ai",
          },
          improveWriting: {
            enabled: true,
            providerId: "read-frog-free-ai",
          },
        },
      },
      betaExperience: {
        enabled: false,
      },
      contextMenu: {
        enabled: true,
      },
      videoSubtitles: {
        enabled: false,
        autoStart: false,
        providerId: "google-default",
        style: {
          displayMode: "bilingual",
          translationPosition: "above",
          main: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          translation: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          container: {
            backgroundOpacity: 75,
          },
          customCSS: null,
        },
        aiSegmentation: false,
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        customPromptsConfig: {
          promptId: "legacy-subtitles-prompt",
          patterns: [
            {
              id: "legacy-subtitles-prompt",
              name: "Legacy Subtitles Prompt",
              systemPrompt:
                "Translate subtitles into {{targetLanguage}} with {{webTitle}} and {{videoSummary}} as context.",
              prompt:
                "Title: {{webTitle}}\nSummary: {{videoSummary}}\nTranslate to {{targetLanguage}}:\n{{input}}",
            },
          ],
        },
        position: {
          percent: 10,
          anchor: "bottom",
        },
        toggleShortcut: "Alt+C",
      },
      inputTranslation: {
        enabled: true,
        providerId: "google-default",
        fromLang: "targetCode",
        toLang: "sourceCode",
        enableCycle: false,
        timeThreshold: 300,
      },
      siteControl: {
        mode: "blacklist",
        blacklistPatterns: [],
        whitelistPatterns: [],
      },
      languageDetection: {
        mode: "basic",
        providerId: "google-default",
      },
      uiLanguage: "auto",
      glossary: {
        enabled: true,
      },
    },
  },
  "default-dictionary-wording": {
    description: "Renames dictionary wording from context to paragraphs",
    config: {
      translationHub: {
        shortcut: "Alt+Shift+H",
        selectedProviderIds: null,
        sourceCode: null,
        targetCode: null,
        promptId: "default",
      },
      siteRules: {
        userRules: [],
        disabledBuiltInRules: [],
      },
      language: {
        sourceCode: "eng",
        targetCode: "cmn",
        level: "intermediate",
      },
      providersConfig: [
        {
          id: "jalapenocloud-default",
          name: "Jalapeno Cloud",
          enabled: true,
          provider: "jalapenocloud",
          description: "Enterprise-grade AI used by top teams — now made for you!",
          baseURL: "https://api.jalapeno-cloud.ai/v1",
          model: {
            model: "DeepSeek-V4-Flash",
            isCustomModel: false,
            customModel: null,
          },
          providerOptions: {
            chat_template_kwargs: {
              thinking: false,
            },
          },
        },
        {
          id: "google-default",
          enabled: true,
          name: "Gemini",
          provider: "google",
          description: "Google's flagship AI models with advanced reasoning capabilities",
          reasoning: "none",
          apiKey: "goog-key",
          model: {
            model: "gemini-2.5-pro",
            isCustomModel: false,
            customModel: "",
          },
        },
      ],
      pageTranslation: {
        providerId: "google-default",
        mode: "translationOnly",
        modeShortcut: "Alt+Shift+M",
        enableAIContentAware: false,
        node: {
          enabled: true,
          hotkey: "alt",
          forceRetranslation: false,
        },
        page: {
          range: "all",
          autoTranslatePatterns: [],
          neverAutoTranslatePatterns: [],
          autoTranslateLanguages: [],
          shortcut: "Alt+B",
          preload: {
            margin: 1000,
            threshold: 0,
          },
          minCharactersPerNode: 0,
          minWordsPerNode: 0,
          enableTargetLanguageSkip: true,
          skipLanguages: [],
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        translationNodeStyle: {
          preset: "default",
          isCustom: false,
          customCSS: null,
        },
      },
      tts: {
        defaultVoice: "en-US-GuyNeural",
        languageVoices: {
          eng: "en-US-GuyNeural",
          cmn: "zh-CN-YunxiNeural",
          "cmn-Hant": "zh-TW-YunJheNeural",
          yue: "zh-CN-YunxiNeural",
          spa: "es-ES-AlvaroNeural",
          rus: "ru-RU-DmitryNeural",
          arb: "ar-SA-HamedNeural",
          ben: "bn-BD-NabanitaNeural",
          hin: "hi-IN-MadhurNeural",
          por: "pt-BR-AntonioNeural",
          ind: "id-ID-ArdiNeural",
          jpn: "ja-JP-KeitaNeural",
          fra: "fr-FR-HenriNeural",
          deu: "de-DE-ConradNeural",
          jav: "jv-ID-DimasNeural",
          kor: "ko-KR-InJoonNeural",
          tel: "te-IN-MohanNeural",
          vie: "vi-VN-NamMinhNeural",
          mar: "mr-IN-ManoharNeural",
          ita: "it-IT-DiegoNeural",
          tam: "ta-IN-ValluvarNeural",
          tur: "tr-TR-AhmetNeural",
          urd: "ur-PK-AsadNeural",
          guj: "gu-IN-NiranjanNeural",
          pol: "pl-PL-MarekNeural",
          ukr: "uk-UA-OstapNeural",
          kan: "kn-IN-GaganNeural",
          mai: "en-US-GuyNeural",
          mal: "ml-IN-MidhunNeural",
          pes: "fa-IR-FaridNeural",
          mya: "my-MM-ThihaNeural",
          swh: "sw-KE-RafikiNeural",
          sun: "su-ID-JajangNeural",
          ron: "ro-RO-EmilNeural",
          pan: "pa-IN-OjasNeural",
          bho: "en-US-GuyNeural",
          amh: "am-ET-AmehaNeural",
          hau: "ha-NG-AbubakarNeural",
          fuv: "ff-Latn-SN-SambaNeural",
          bos: "bs-BA-GoranNeural",
          hrv: "hr-HR-SreckoNeural",
          nld: "nl-NL-MaartenNeural",
          srp: "sr-RS-NicholasNeural",
          tha: "th-TH-NiwatNeural",
          ckb: "en-US-GuyNeural",
          yor: "yo-NG-AbeoNeural",
          uzn: "uz-UZ-SardorNeural",
          zlm: "ms-MY-OsmanNeural",
          ibo: "ig-NG-EzinneNeural",
          npi: "ne-NP-SagarNeural",
          ceb: "en-US-GuyNeural",
          skr: "en-US-GuyNeural",
          tgl: "fil-PH-AngeloNeural",
          hun: "hu-HU-TamasNeural",
          azj: "az-AZ-BabekNeural",
          sin: "si-LK-SameeraNeural",
          koi: "en-US-GuyNeural",
          ell: "el-GR-NestorasNeural",
          ces: "cs-CZ-AntoninNeural",
          mag: "en-US-GuyNeural",
          run: "en-US-GuyNeural",
          bel: "be-BY-YauheniNeural",
          plt: "en-US-GuyNeural",
          qug: "en-US-GuyNeural",
          mad: "en-US-GuyNeural",
          nya: "en-US-GuyNeural",
          zyb: "en-US-GuyNeural",
          pbu: "en-US-GuyNeural",
          kin: "rw-RW-JeanNeural",
          zul: "zu-ZA-ThembaNeural",
          bul: "bg-BG-BorislavNeural",
          swe: "sv-SE-MattiasNeural",
          lin: "ln-CD-BaudouinNeural",
          som: "so-SO-MuuseNeural",
          hms: "en-US-GuyNeural",
          hnj: "en-US-GuyNeural",
          ilo: "en-US-GuyNeural",
          kaz: "kk-KZ-DauletNeural",
          heb: "he-IL-AvriNeural",
          nob: "nb-NO-FinnNeural",
          nno: "nn-NO-FinnNeural",
          afr: "af-ZA-AdriNeural",
          sqi: "sq-AL-IlirNeural",
          asm: "as-IN-BiswajitNeural",
          eus: "eu-ES-AnderNeural",
          bre: "fr-FR-HenriNeural",
          cat: "ca-ES-EnricNeural",
          cos: "fr-FR-HenriNeural",
          cym: "cy-GB-AledNeural",
          dan: "da-DK-JeppeNeural",
          div: "si-LK-SameeraNeural",
          epo: "en-US-GuyNeural",
          ekk: "et-EE-KertNeural",
          fao: "fo-FO-PoulNeural",
          fij: "en-US-GuyNeural",
          fin: "fi-FI-HarriNeural",
          fry: "nl-NL-MaartenNeural",
          gla: "en-GB-RyanNeural",
          gle: "ga-IE-ColmNeural",
          glg: "gl-ES-RoiNeural",
          grn: "es-ES-AlvaroNeural",
          hat: "fr-FR-HenriNeural",
          haw: "en-US-GuyNeural",
          hye: "hy-AM-HaykNeural",
          ido: "en-US-GuyNeural",
          ina: "en-US-GuyNeural",
          isl: "is-IS-GunnarNeural",
          kat: "ka-GE-GiorgiNeural",
          khm: "km-KH-PisethNeural",
          kir: "kk-KZ-DauletNeural",
          lao: "lo-LA-ChanthavongNeural",
          lat: "it-IT-DiegoNeural",
          lvs: "lv-LV-NilsNeural",
          lit: "lt-LT-LeonasNeural",
          ltz: "fr-FR-HenriNeural",
          mkd: "mk-MK-AleksandarNeural",
          mlt: "mt-MT-JosephNeural",
          mon: "mn-MN-BataaNeural",
          mri: "en-NZ-MitchellNeural",
          nso: "en-US-GuyNeural",
          oci: "fr-FR-HenriNeural",
          ori: "or-IN-DineshNeural",
          orm: "en-US-GuyNeural",
          prs: "en-US-GuyNeural",
          san: "hi-IN-MadhurNeural",
          slk: "sk-SK-LukasNeural",
          slv: "sl-SI-RokNeural",
          smo: "en-US-GuyNeural",
          sna: "en-US-GuyNeural",
          snd: "sd-PK-SalmanNeural",
          sot: "en-US-GuyNeural",
          tah: "fr-FR-HenriNeural",
          tat: "tt-RU-AidarNeural",
          tgk: "tg-TJ-SharifNeural",
          tir: "am-ET-AmehaNeural",
          ton: "en-US-GuyNeural",
          tsn: "en-US-GuyNeural",
          tuk: "tk-TM-AmanNeural",
          uig: "ug-CN-KashgarNeural",
          vol: "en-US-GuyNeural",
          wol: "en-US-GuyNeural",
          xho: "xh-ZA-ThembaNeural",
          ydd: "he-IL-AvriNeural",
          aka: "en-US-GuyNeural",
          bam: "fr-FR-HenriNeural",
          bis: "en-US-GuyNeural",
          bod: "zh-CN-YunxiNeural",
          che: "ru-RU-DmitryNeural",
          chv: "ru-RU-DmitryNeural",
          dzo: "zh-CN-YunxiNeural",
          ewe: "en-US-GuyNeural",
          kab: "en-US-GuyNeural",
          lug: "en-US-GuyNeural",
          oss: "ru-RU-DmitryNeural",
          ssw: "en-US-GuyNeural",
          ven: "en-US-GuyNeural",
          war: "en-US-GuyNeural",
          nde: "en-US-GuyNeural",
          nbl: "en-US-GuyNeural",
          pam: "en-US-GuyNeural",
          hil: "en-US-GuyNeural",
          bcl: "en-US-GuyNeural",
          min: "en-US-GuyNeural",
          ace: "en-US-GuyNeural",
          bug: "en-US-GuyNeural",
          ban: "en-US-GuyNeural",
          bjn: "en-US-GuyNeural",
          mak: "en-US-GuyNeural",
          sas: "en-US-GuyNeural",
          tet: "en-US-GuyNeural",
          cha: "en-US-GuyNeural",
          niu: "en-US-GuyNeural",
          tvl: "en-US-GuyNeural",
          gil: "en-US-GuyNeural",
          mah: "en-US-GuyNeural",
          pau: "en-US-GuyNeural",
          wls: "en-US-GuyNeural",
          rar: "en-US-GuyNeural",
          hif: "en-US-GuyNeural",
        },
        rate: 0,
        pitch: 0,
        volume: 0,
      },
      floatingButton: {
        enabled: true,
        position: 0.5,
        disabledFloatingButtonPatterns: [],
        clickAction: "panel",
        locked: false,
        side: "right",
      },
      sideContent: {
        width: 420,
      },
      selectionToolbar: {
        order: [
          "translate",
          "speak",
          "default-dictionary",
          "default-sentence-analysis",
          "default-improve-writing",
        ],
        unpinned: ["default-improve-writing"],
        noteSuggestion: {
          enabled: true,
          actionId: "default-dictionary",
          providerId: "google-default",
        },
        enabled: true,
        disabledSelectionToolbarPatterns: [],
        opacity: 100,
        customActions: [],
        features: {
          translate: {
            enabled: true,
            providerId: "google-default",
            shortcut: "Alt+T",
          },
          speak: {
            enabled: true,
          },
        },
        builtInActions: {
          dictionary: {
            enabled: true,
            providerId: "google-default",
          },
          sentenceAnalysis: {
            enabled: true,
            providerId: "google-default",
          },
          improveWriting: {
            enabled: true,
            providerId: "google-default",
          },
        },
      },
      betaExperience: {
        enabled: false,
      },
      contextMenu: {
        enabled: true,
      },
      videoSubtitles: {
        enabled: false,
        autoStart: false,
        providerId: "google-default",
        style: {
          displayMode: "bilingual",
          translationPosition: "above",
          main: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          translation: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          container: {
            backgroundOpacity: 75,
          },
          customCSS: null,
        },
        aiSegmentation: false,
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        position: {
          percent: 10,
          anchor: "bottom",
        },
        toggleShortcut: "Alt+C",
      },
      inputTranslation: {
        enabled: true,
        providerId: "google-default",
        fromLang: "targetCode",
        toLang: "sourceCode",
        enableCycle: false,
        timeThreshold: 300,
      },
      siteControl: {
        mode: "blacklist",
        blacklistPatterns: [],
        whitelistPatterns: [],
      },
      languageDetection: {
        mode: "basic",
        providerId: "google-default",
      },
      uiLanguage: "auto",
      glossary: {
        enabled: true,
      },
    },
  },
  "custom-action-with-custom-layout": {
    description:
      "v103 only: a custom action with a hand-written layout using bracket refs, CJK field names and an escaped %",
    config: {
      translationHub: {
        shortcut: "Alt+Shift+H",
        selectedProviderIds: null,
        sourceCode: null,
        targetCode: null,
        promptId: "default",
      },
      siteRules: {
        userRules: [],
        disabledBuiltInRules: [],
      },
      language: {
        sourceCode: "eng",
        targetCode: "cmn",
        level: "intermediate",
      },
      providersConfig: [
        {
          id: "jalapenocloud-default",
          name: "Jalapeno Cloud",
          enabled: true,
          provider: "jalapenocloud",
          description: "Enterprise-grade AI used by top teams — now made for you!",
          baseURL: "https://api.jalapeno-cloud.ai/v1",
          model: {
            model: "DeepSeek-V4-Flash",
            isCustomModel: false,
            customModel: null,
          },
          providerOptions: {
            chat_template_kwargs: {
              thinking: false,
            },
          },
        },
        {
          id: "google-default",
          enabled: true,
          name: "Gemini",
          provider: "google",
          description: "Google's flagship AI models with advanced reasoning capabilities",
          reasoning: "none",
          apiKey: "goog-key",
          model: {
            model: "gemini-2.5-pro",
            isCustomModel: false,
            customModel: "",
          },
        },
      ],
      pageTranslation: {
        providerId: "google-default",
        mode: "translationOnly",
        modeShortcut: "Alt+Shift+M",
        enableAIContentAware: false,
        node: {
          enabled: true,
          hotkey: "alt",
          forceRetranslation: false,
        },
        page: {
          range: "all",
          autoTranslatePatterns: [],
          neverAutoTranslatePatterns: [],
          autoTranslateLanguages: [],
          shortcut: "Alt+B",
          preload: {
            margin: 1000,
            threshold: 0,
          },
          minCharactersPerNode: 0,
          minWordsPerNode: 0,
          enableTargetLanguageSkip: true,
          skipLanguages: [],
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        translationNodeStyle: {
          preset: "default",
          isCustom: false,
          customCSS: null,
        },
      },
      tts: {
        defaultVoice: "en-US-GuyNeural",
        languageVoices: {
          eng: "en-US-GuyNeural",
          cmn: "zh-CN-YunxiNeural",
          "cmn-Hant": "zh-TW-YunJheNeural",
          yue: "zh-CN-YunxiNeural",
          spa: "es-ES-AlvaroNeural",
          rus: "ru-RU-DmitryNeural",
          arb: "ar-SA-HamedNeural",
          ben: "bn-BD-NabanitaNeural",
          hin: "hi-IN-MadhurNeural",
          por: "pt-BR-AntonioNeural",
          ind: "id-ID-ArdiNeural",
          jpn: "ja-JP-KeitaNeural",
          fra: "fr-FR-HenriNeural",
          deu: "de-DE-ConradNeural",
          jav: "jv-ID-DimasNeural",
          kor: "ko-KR-InJoonNeural",
          tel: "te-IN-MohanNeural",
          vie: "vi-VN-NamMinhNeural",
          mar: "mr-IN-ManoharNeural",
          ita: "it-IT-DiegoNeural",
          tam: "ta-IN-ValluvarNeural",
          tur: "tr-TR-AhmetNeural",
          urd: "ur-PK-AsadNeural",
          guj: "gu-IN-NiranjanNeural",
          pol: "pl-PL-MarekNeural",
          ukr: "uk-UA-OstapNeural",
          kan: "kn-IN-GaganNeural",
          mai: "en-US-GuyNeural",
          mal: "ml-IN-MidhunNeural",
          pes: "fa-IR-FaridNeural",
          mya: "my-MM-ThihaNeural",
          swh: "sw-KE-RafikiNeural",
          sun: "su-ID-JajangNeural",
          ron: "ro-RO-EmilNeural",
          pan: "pa-IN-OjasNeural",
          bho: "en-US-GuyNeural",
          amh: "am-ET-AmehaNeural",
          hau: "ha-NG-AbubakarNeural",
          fuv: "ff-Latn-SN-SambaNeural",
          bos: "bs-BA-GoranNeural",
          hrv: "hr-HR-SreckoNeural",
          nld: "nl-NL-MaartenNeural",
          srp: "sr-RS-NicholasNeural",
          tha: "th-TH-NiwatNeural",
          ckb: "en-US-GuyNeural",
          yor: "yo-NG-AbeoNeural",
          uzn: "uz-UZ-SardorNeural",
          zlm: "ms-MY-OsmanNeural",
          ibo: "ig-NG-EzinneNeural",
          npi: "ne-NP-SagarNeural",
          ceb: "en-US-GuyNeural",
          skr: "en-US-GuyNeural",
          tgl: "fil-PH-AngeloNeural",
          hun: "hu-HU-TamasNeural",
          azj: "az-AZ-BabekNeural",
          sin: "si-LK-SameeraNeural",
          koi: "en-US-GuyNeural",
          ell: "el-GR-NestorasNeural",
          ces: "cs-CZ-AntoninNeural",
          mag: "en-US-GuyNeural",
          run: "en-US-GuyNeural",
          bel: "be-BY-YauheniNeural",
          plt: "en-US-GuyNeural",
          qug: "en-US-GuyNeural",
          mad: "en-US-GuyNeural",
          nya: "en-US-GuyNeural",
          zyb: "en-US-GuyNeural",
          pbu: "en-US-GuyNeural",
          kin: "rw-RW-JeanNeural",
          zul: "zu-ZA-ThembaNeural",
          bul: "bg-BG-BorislavNeural",
          swe: "sv-SE-MattiasNeural",
          lin: "ln-CD-BaudouinNeural",
          som: "so-SO-MuuseNeural",
          hms: "en-US-GuyNeural",
          hnj: "en-US-GuyNeural",
          ilo: "en-US-GuyNeural",
          kaz: "kk-KZ-DauletNeural",
          heb: "he-IL-AvriNeural",
          nob: "nb-NO-FinnNeural",
          nno: "nn-NO-FinnNeural",
          afr: "af-ZA-AdriNeural",
          sqi: "sq-AL-IlirNeural",
          asm: "as-IN-BiswajitNeural",
          eus: "eu-ES-AnderNeural",
          bre: "fr-FR-HenriNeural",
          cat: "ca-ES-EnricNeural",
          cos: "fr-FR-HenriNeural",
          cym: "cy-GB-AledNeural",
          dan: "da-DK-JeppeNeural",
          div: "si-LK-SameeraNeural",
          epo: "en-US-GuyNeural",
          ekk: "et-EE-KertNeural",
          fao: "fo-FO-PoulNeural",
          fij: "en-US-GuyNeural",
          fin: "fi-FI-HarriNeural",
          fry: "nl-NL-MaartenNeural",
          gla: "en-GB-RyanNeural",
          gle: "ga-IE-ColmNeural",
          glg: "gl-ES-RoiNeural",
          grn: "es-ES-AlvaroNeural",
          hat: "fr-FR-HenriNeural",
          haw: "en-US-GuyNeural",
          hye: "hy-AM-HaykNeural",
          ido: "en-US-GuyNeural",
          ina: "en-US-GuyNeural",
          isl: "is-IS-GunnarNeural",
          kat: "ka-GE-GiorgiNeural",
          khm: "km-KH-PisethNeural",
          kir: "kk-KZ-DauletNeural",
          lao: "lo-LA-ChanthavongNeural",
          lat: "it-IT-DiegoNeural",
          lvs: "lv-LV-NilsNeural",
          lit: "lt-LT-LeonasNeural",
          ltz: "fr-FR-HenriNeural",
          mkd: "mk-MK-AleksandarNeural",
          mlt: "mt-MT-JosephNeural",
          mon: "mn-MN-BataaNeural",
          mri: "en-NZ-MitchellNeural",
          nso: "en-US-GuyNeural",
          oci: "fr-FR-HenriNeural",
          ori: "or-IN-DineshNeural",
          orm: "en-US-GuyNeural",
          prs: "en-US-GuyNeural",
          san: "hi-IN-MadhurNeural",
          slk: "sk-SK-LukasNeural",
          slv: "sl-SI-RokNeural",
          smo: "en-US-GuyNeural",
          sna: "en-US-GuyNeural",
          snd: "sd-PK-SalmanNeural",
          sot: "en-US-GuyNeural",
          tah: "fr-FR-HenriNeural",
          tat: "tt-RU-AidarNeural",
          tgk: "tg-TJ-SharifNeural",
          tir: "am-ET-AmehaNeural",
          ton: "en-US-GuyNeural",
          tsn: "en-US-GuyNeural",
          tuk: "tk-TM-AmanNeural",
          uig: "ug-CN-KashgarNeural",
          vol: "en-US-GuyNeural",
          wol: "en-US-GuyNeural",
          xho: "xh-ZA-ThembaNeural",
          ydd: "he-IL-AvriNeural",
          aka: "en-US-GuyNeural",
          bam: "fr-FR-HenriNeural",
          bis: "en-US-GuyNeural",
          bod: "zh-CN-YunxiNeural",
          che: "ru-RU-DmitryNeural",
          chv: "ru-RU-DmitryNeural",
          dzo: "zh-CN-YunxiNeural",
          ewe: "en-US-GuyNeural",
          kab: "en-US-GuyNeural",
          lug: "en-US-GuyNeural",
          oss: "ru-RU-DmitryNeural",
          ssw: "en-US-GuyNeural",
          ven: "en-US-GuyNeural",
          war: "en-US-GuyNeural",
          nde: "en-US-GuyNeural",
          nbl: "en-US-GuyNeural",
          pam: "en-US-GuyNeural",
          hil: "en-US-GuyNeural",
          bcl: "en-US-GuyNeural",
          min: "en-US-GuyNeural",
          ace: "en-US-GuyNeural",
          bug: "en-US-GuyNeural",
          ban: "en-US-GuyNeural",
          bjn: "en-US-GuyNeural",
          mak: "en-US-GuyNeural",
          sas: "en-US-GuyNeural",
          tet: "en-US-GuyNeural",
          cha: "en-US-GuyNeural",
          niu: "en-US-GuyNeural",
          tvl: "en-US-GuyNeural",
          gil: "en-US-GuyNeural",
          mah: "en-US-GuyNeural",
          pau: "en-US-GuyNeural",
          wls: "en-US-GuyNeural",
          rar: "en-US-GuyNeural",
          hif: "en-US-GuyNeural",
        },
        rate: 0,
        pitch: 0,
        volume: 0,
      },
      floatingButton: {
        enabled: true,
        position: 0.5,
        disabledFloatingButtonPatterns: [],
        clickAction: "panel",
        locked: false,
        side: "right",
      },
      sideContent: {
        width: 420,
      },
      selectionToolbar: {
        order: [
          "translate",
          "speak",
          "default-dictionary",
          "default-sentence-analysis",
          "default-improve-writing",
          "vocab-card",
        ],
        unpinned: ["default-improve-writing"],
        noteSuggestion: {
          enabled: true,
          actionId: "default-dictionary",
          providerId: "google-default",
        },
        enabled: true,
        disabledSelectionToolbarPatterns: [],
        opacity: 100,
        customActions: [
          {
            id: "vocab-card",
            name: "生词卡",
            enabled: true,
            icon: "tabler:cards",
            providerId: "google-default",
            systemPrompt: "",
            prompt: "Explain {{selection}} in {{targetLanguage}}.",
            outputSchema: [
              {
                id: "vocab-term",
                name: "词条",
                type: "string",
                description: "The word itself.",
              },
              {
                id: "vocab-meaning",
                name: "释义 (简明)",
                type: "string",
                description: "One short sense.",
              },
              {
                id: "vocab-mastery",
                name: "掌握度 %",
                type: "number",
                description: "0 to 100.",
              },
            ],
            // Stored text holds a literal backslash: `\\u0025` here is `\u0025` in the layout.
            layout: `<style>
.vc{display:flex;flex-direction:column;gap:6px}
.vc-bar{height:4px;width:100%;background:var(--rf-muted)}
</style>
<div class="vc" data-rf-key="vc">
  {%- assign term = ["词条"] -%}
  <strong data-speak="">{{ term }}</strong>
  {%- if ["释义 (简明)"] != blank %}
  <p>{{ ["释义 (简明)"] | newline_to_br }}</p>
  {%- endif %}
  <span class="vc-bar" data-rf-key="vc-bar"></span>
  <small>{{ ["掌握度 \\u0025"] | default: 0 }}/100</small>
</div>
`,
          },
        ],
        features: {
          translate: {
            enabled: true,
            providerId: "google-default",
            shortcut: "Alt+T",
          },
          speak: {
            enabled: true,
          },
        },
        builtInActions: {
          dictionary: {
            enabled: true,
            providerId: "google-default",
          },
          sentenceAnalysis: {
            enabled: true,
            providerId: "google-default",
          },
          improveWriting: {
            enabled: true,
            providerId: "google-default",
          },
        },
      },
      betaExperience: {
        enabled: false,
      },
      contextMenu: {
        enabled: true,
      },
      videoSubtitles: {
        enabled: false,
        autoStart: false,
        providerId: "google-default",
        style: {
          displayMode: "bilingual",
          translationPosition: "above",
          main: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          translation: {
            fontFamily: "system",
            fontScale: 100,
            color: "#FFFFFF",
            fontWeight: 400,
          },
          container: {
            backgroundOpacity: 75,
          },
          customCSS: null,
        },
        aiSegmentation: false,
        requestQueueConfig: {
          capacity: 200,
          rate: 2,
        },
        batchQueueConfig: {
          maxCharactersPerBatch: 1000,
          maxItemsPerBatch: 4,
        },
        customPromptsConfig: {
          promptId: "default",
          patterns: [],
        },
        position: {
          percent: 10,
          anchor: "bottom",
        },
        toggleShortcut: "Alt+C",
      },
      inputTranslation: {
        enabled: true,
        providerId: "google-default",
        fromLang: "targetCode",
        toLang: "sourceCode",
        enableCycle: false,
        timeThreshold: 300,
      },
      siteControl: {
        mode: "blacklist",
        blacklistPatterns: [],
        whitelistPatterns: [],
      },
      languageDetection: {
        mode: "basic",
        providerId: "google-default",
      },
      uiLanguage: "auto",
      glossary: {
        enabled: true,
      },
    },
  },
}
